version: '3.8'
services:
  dev-db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgressDB
    networks:
      - nestcrud
networks:
  nestcrud:
